version: '3.3'

services:
  mysql:
    image: mysql:8
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: finsol
      MYSQL_DATABASE: sampley
    ports:
      - "3306:3306"
    networks:
      - app-network
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    container_name: spring-app
    restart: on-failure
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/sampley
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: finsol
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MySQL8Dialect
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: "true"
      SPRING_APPLICATION_NAME: simplejavaproject
      SERVER_PORT: 8092
    ports:
      - "8092:8092"
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge
