apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "finsol"
            - name: MYSQL_DATABASE
              value: "sampley"
          ports:
            - containerPort: 3306
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-storage  # Mount the persistent volume here
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-pvc  # PVC for persistent storage

---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: mysql
  clusterIP: None  # Headless service for direct connection, or remove for regular service

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc  # Define the PVC to request persistent storage
spec:
  accessModes:
    - ReadWriteOnce  # Only one pod can mount this volume at a time
  resources:
    requests:
      storage: 1Gi  # Storage size, adjust based on your needs