apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot
  template:
    metadata:
      labels:
        app: springboot
    spec:
      containers:
        - name: springboot
          image: k8s_springboot_project:latest  # Local image
          imagePullPolicy: Never  # Prevents pulling from remote registry
          ports:
            - containerPort: 8092
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/sampley
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: finsol
            - name: SPRING_JPA_DATABASE_PLATFORM
              value: org.hibernate.dialect.MySQL8Dialect
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: update
            - name: SPRING_JPA_SHOW_SQL
              value: "true"
            - name: SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL
              value: "true"
            - name: SPRING_APPLICATION_NAME
              value: simplejavaproject
            - name: SERVER_PORT
              value: "8092"
---
apiVersion: v1
kind: Service
metadata:
  name: springboot-service
spec:
  selector:
    app: springboot  # The label should match the deployment's label
  ports:
    - port: 8092
      targetPort: 8092
  type: NodePort

